# Generated by Django 4.1.2 on 2022-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('price', models.CharField(max_length=120)),
                ('one_hour', models.CharField(max_length=120)),
                ('twenty_four_hour', models.CharField(max_length=120)),
                ('seven_days', models.CharField(max_length=120)),
                ('market_cap', models.CharField(max_length=120)),
                ('volume_24', models.CharField(max_length=120)),
            ],
        ),
    ]
